### ISSUE TITLE
error(nostalgia)

### ISSUE THREAD

**Issue by motuson** [terascripter/TeraCZ-Toolbox#2]
[command] ERROR: TypeError: Cannot read property 'toUpperCase' of undefined
    at String.<anonymous> (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\mods\nostalgia\index.js:148:17)
    at CommandBase.exec (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\mods\command\index.js:168:16)
    at hookCommand (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\mods\command\index.js:46:30)
    at Object.callback (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\mods\command\index.js:56:29)
    at Dispatch.handle (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:465:45)
    at Socket.<anonymous> (C:\Users\*****\Desktop\Новая папка\TeraCZ-Toolbox-master\node_modules\tera-network-proxy\lib\clients\RealClient.js:38:31)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)

**Comment by terascripter** [comment]
you probably typed only "tp", you need to type "tp" + the dungeon. example: "tp abhm"
